# nixpacks.toml

[phases.setup]
# "..."       -> Includes default Nixpacks packages
# "python3"   -> Adds Python for node-gyp
# "gcc"       -> Adds the C++ compiler (g++) for native addons
# "nodejs_22" -> Upgrades Node.js to resolve the warning
# "npm-10_x"  -> Upgrades npm to match the newer Node.js
nixPkgs = ["...", "python3", "gcc", "nodejs_22", "npm-10_x"]

[start]
cmd = "npm run start"