# nixpacks.toml

[phases.setup]
# "..." tells Nixpacks to include its default setup first (which includes Node.js and npm).
# Then, we ADD the extra packages we need (python3 and gcc).
nixPkgs = ["...", "python3", "gcc"]

[start]
cmd = "npm run start"